### PR TITLE
feat: props: normalize label, classnames, button alignment and iconprops

### PR DESCRIPTION
**Pull request by dkilgore-eightfold**
This PR contains a BREAKING CHANGE:

classnames and icon props must be updated to match latest

Additionally:

- Moves Label into its own component
- Exposes Icon props like, spin and rotate
- Adds button alignIcon prop to render its icon on the left or right side of its text

### CODE REVIEW

**Comment by thiyagaraj-eightfold** [comment]
reopening to trigger tests

**Comment by ychhabra-eightfold** [comment]
@dkilgore-eightfold build is breaking cause of 

/home/runner/work/octuple/octuple/src/components/MatchScore/MatchScore.tsx(3,10)\n' +
[205](https://github.com/EightfoldAI/octuple/runs/6265916429?check_suite_focus=true#step:5:205)
    `      TS2305: Module '"../../shared/utilities"' has no exported member 'classNames'.\x1B[39m\x1B[22m\n` +
[206](https://github.com/EightfoldAI/octuple/runs/6265916429?check_suite_focus=true#step:5:206)
    ' @ ./src/components/MatchScore/index.ts 17:13-36\n' +

**Comment by thiyagaraj-eightfold** [comment]
Hey - why don’t you try a component approach for this. 
example - `<Atom classNames={[...]} element='div' /> `

So `<Atom/>` or `<BaseElement/>` becomes a primitive component that can be used across the lib.
This will abstract how we are merging the classes etc.
We can always refactor the atom class in the future without really disturbing the API of the component

**Review by ychhabra-eightfold — APPROVED** [review]
LGTM

**Comment by dkilgore-eightfold** [comment]
> Hey - why don’t you try a component approach for this. example - `<Atom classNames={[...]} element='div' /> `
> 
> So `<Atom/>` or `<BaseElement/>` becomes a primitive component that can be used across the lib. This will abstract how we are merging the classes etc. We can always refactor the atom class in the future without really disturbing the API of the component

Let's discuss this approach. Sounds like a good one. Maybe we could create a wrapping component.

**Pull request merged**
